spring:
  datasource:
    name: "local-users-db"
    url: "jdbc:postgresql://localhost:5433/cleverhause_users_db"
    username: 'clever_admin'
    password: 'WindowsVista123'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: 'org.hibernate.dialect.PostgreSQL95Dialect'
      hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
      hibernate.connection.characterEncoding: "UTF-8"
      hibernate.connection.charSet: "UTF-8"
      hibernate.temp.use_jdbc_metadata_defaults: "true"
      hibernate.physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  liquibase:
    enabled: false
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 'b4ccc96cfd49bff036a6'
            clientSecret: '178119e291c3b07a4684d1b31c35bb94b058329d'
            # need to do that if your redirect-uri differs from default one which is based on server port and host
            # (for local will be http://localhost:[server.port]/login/oauth2/code)
            redirect_uri: 'http://cleverhause.ru/login/oauth2/code/github'
            clientAuthenticationMethod: 'post'
          google:
            clientId: '400048896634-acal0divdad68tug694b4ifuhcdh71v9.apps.googleusercontent.com'
            clientSecret: 'qjKeuzeTaN2M9GWfDTYv1qLB'

feign:
  clients:
    auth-server:
      name: "cleverhause-auth"
      url: "http://localhost:8081"
      path: "/oauth/token"
      retryer:
        # time period after which we will repeat request
        period: 1000
        # max time period after which we will repeat request
        maxPeriod: 1000
        maxAttempts: 1
      oauth2:
        enabled: true
        resource:
          id: "cleverhause-auth"
          clientId: "cleverhause-users"
          clientSecret: "secret"
#          TODO bug #62
          scope: "all"
          accessTokenUri: "http://localhost:8081/oauth/token"
          type: "client_credentials"